services:
  poker-front:
    build:
      context: ./front-poker-api
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      - "5173:5173"
    container_name: poker-front
    depends_on:
      - poker-api
    networks:
      - poker_app
    volumes:
      - './front-poker-api:/app'

  poker-api:
    build:
      context: ./back-poker-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    container_name: poker-api
    networks:
      - poker_app
    volumes:
      - './back-poker-api:/app'
    environment:
      - MONGODB_URI=${MONGODB_URI}
    command: sh -c "npm run start:prod"

networks:
  poker_app:
    driver: bridge  